import $ from 'jquery'
import { getFirst , getTranslateAttr } from './misc'
import trFilterVisio2013    from './trFilterVisio2013'

const loadXML = url => {
  return new Promise( (resolve,reject) => {
    fetch( url )
    .then( res => {
      if( res.ok ){ 
        res.text()
        .then( xml => { resolve( xml ) } )
        .catch( err => { reject( err ) } ) 
      }
      else{ reject( Error( url + ' Not found!') ) } 
    })
    .catch( err => { reject( err ) } )
  })
}

export const injectMap = ( div , id ) => {
  return new Promise( ( resolve , reject ) => {
    let url = ( AMAPS_CONF && AMAPS_CONF.repository ? AMAPS_CONF.repository : './maps/' ) + id + '.svg'
    loadXML( url )
    .then( svg => {
      if( svg.indexOf("Generated by Microsoft Visio") >= 0 ){ return trFilterVisio2013( svg ) }
      return new Promise( ( resolve , reject ) => resolve( svg )  ) 
    } )
    .then(  svg => { div.innerHTML = svg ; resolve( div ) } )
    .catch( err => { div.innerHTML = "<p>Sorry! An error has occurred:<br>" + err +"</p>"; reject( err ) } ) 
  } )
}

export const fitMap = ( div , targetDisplay ) => {
  return new Promise( ( resolve , reject ) => { 

    let svg = getFirst( $( div ).find('svg') )
    if( svg ){
      let viewBox = { x:0 , y:0 , w:100 , h:100 }
      let display = getFirst( $( svg ).find('[data-amaps-display="' + targetDisplay + '"]') )
      if( display ){
        let translate = getTranslateAttr( display )
        let rect = getFirst( $( display ).find('rect') )
        if( rect ){
          viewBox = {
            x:Math.round( 1*rect.getAttribute('x') + translate.x ),
            y:Math.round( 1*rect.getAttribute('y') + translate.y ),
            w:Math.round( 1*rect.getAttribute('width')),
            h:Math.round( 1*rect.getAttribute('height'))
          }
        }
      }
      svg.setAttribute( 'viewBox' , ''+ viewBox.x +' '+ viewBox.y +' '+ viewBox.w +' '+ viewBox.h )
      svg.setAttribute( 'width'   , ''+ div.offsetWidth +'px' )
      svg.setAttribute( 'height'  , ''+ viewBox.h * div.offsetWidth / viewBox.w +'px' )

      resolve ()
    }else{ reject( Error('Could not find SVG object.') ) }
  } )
}
